#!/bin/sh
rm -rf public

dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
echo "dir: $dir"

ssh_host="g22"

if [ "$(uname)" == 'Darwin' ]; then
    # Mac
    iconv="--iconv=UTF-8-MAC,UTF-8"
    hugo017
else
    # WSL or Windows
    iconv=""
    hugo017.exe
fi

rsync ${iconv} -avzc --delete --exclude-from=rsync-exclude ${dir}/public/ ${ssh_host}:/var/www/html/